#The name of the release
name: Release v1.0.10
#Declaring the branches and tags
on:
  push:
    branches:
      - "main"
#Declaring all jobs and flows
jobs:
  release:
    name: Release v1.0.10
    if: "github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[sonar]') && !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      #Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      #Create New Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.10
          release_name: Iqraa v1.0.10
          body: |
            Changes in this Release:
              - [New] Release new version v1.0.10
              - [New] JRE metadata fetch bug fix
          draft: false
          prerelease: false